FROM python:3.7.3-slim
MAINTAINER lapin

RUN apt-get update
RUN apt-get install -y vim

RUN apt-get install -y python3-dev
RUN apt-get install -y unixodbc-dev unixodbc-bin unixodbc freetds-dev tdsodbc

RUN apt-get install -y locales locales-all

COPY ./sources/requirements7.txt /opt/sources/requirements.txt
RUN pip install -r /opt/sources/requirements.txt

RUN apt-get install -y gcc python3-dev python3-pip libxml2-dev libxslt1-dev zlib1g-dev g++
RUN pip install pyodbc

RUN apt-get install -y curl
RUN apt-get install -y apt-transport-https

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update 

RUN ACCEPT_EULA=Y apt-get install msodbcsql17
RUN ACCEPT_EULA=Y apt-get install mssql-tools

COPY ./sources /opt/sources
RUN rm -d -r /opt/sources/logs
RUN mkdir  /opt/sources/logs
RUN rm -d -r /opt/sources/*.sh
WORKDIR /opt/sources
CMD ["python", "nyx_lambda.py"]
